const SOURCE_TYPE = {
  TABLEAU: 'TABLEAU',
  WASTE: 'WASTE_PILE'
};

const TARGET_TYPE = {
  TABLEAU: 'TABLEAU',
  FOUNDATION: 'FOUNDATION'
};

const GAME_STATUS = {
  WON: 'WON',
  IN_PROGRESS: 'IN_PROGRESS'
};

export { SOURCE_TYPE, TARGET_TYPE, GAME_STATUS };
